apiVersion: v2
name: collab-hub
type: application
description: Helm chart for collab-hub-pack
version: "0.2.0"
appVersion: "0.2.0"
home: https://github.com/nebari-dev/collab-hub-pack
sources:
  - https://github.com/nebari-dev/collab-hub-pack
maintainers:
  - name: OpenTeams
    email: info@openteams.com
