apiVersion: v2
name: nebari-operator
description: A Helm chart to distribute nebari-operator
type: application

version: 0.1.0-alpha.16
appVersion: "v0.1.0-alpha.16"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
