{{- if and .Values.api.enabled .Values.api.serviceAccount.create }}
{{- $component := "api" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "collab-hub.api-service-account-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collab-hub.labels" (dict "top" . "component" $component) | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
